In [1]:
from google.colab import drive
import pandas as pd
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
import os
os.chdir("/content/gdrive/MyDrive")
!ls

'2019 葉問4：完結篇.rar'
 71048848-1DB4-4391-BD28-ECF892A146A4.png
'Colab Notebooks'
 course-v4
 CTBC_card_Estatement_10902.pdf
 CTBC_card_Estatement_10903.pdf
'D22 結合 Pandas 與 Matploglib 進行進階資料視覺化練習_HW.ipynb'
 TSB_Creditcard_Estatement_202009.pdf
 winequality_red.csv
 winequality_white.csv
 大立光薪水.xlsx
 智慧整合開發部_黃宗性_工作報告_1222.xlsx
'永續智慧社區送審公文 (1).pdf'
'永續智慧社區送審公文 (2).pdf'
 永續智慧社區送審公文.pdf
 永續智慧社區送審公文.pdf.gdoc
 無標題的試算表.gsheet
 空調組控制板資料--全.rar
 自傳.docx

In [3]:
pd.read_csv('/content/gdrive/MyDrive/winequality_red.csv')

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
path = "/content/gdrive/MyDrive"
os.chdir(path)
os.getcwd()

'/content/gdrive/MyDrive'

In [5]:
pd.read_csv("winequality_white.csv")

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.0              0.27         0.36  ...       0.45      8.8        6
1               6.3              0.30         0.34  ...       0.49      9.5        6
2               8.1              0.28         0.40  ...       0.44     10.1        6
3               7.2              0.23         0.32  ...       0.40      9.9        6
4               7.2              0.23         0.32  ...       0.40      9.9        6
...             ...               ...          ...  ...        ...      ...      ...
4893            6.2              0.21         0.29  ...       0.50     11.2        6
4894            6.6              0.32         0.36  ...       0.46      9.6        5
4895            6.5              0.24         0.19  ...       0.46      9.4        6
4896            5.5              0.29         0.30  ...       0.38     12.8        7
4897            6.0              0.21         0.38  ...       0.32     11.8        6

[4898 rows x 12 columns]

In [6]:
import os
os.chdir("/content/gdrive/MyDrive/Colab Notebooks")
!ls

Untitled0.ipynb

In [7]:
path = "/content/gdrive/MyDrive/Colab Notebooks"
os.chdir(path)
os.getcwd()

'/content/gdrive/MyDrive/Colab Notebooks'

In [8]:
pd.read_csv("winequality_red.csv")

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]